version: 2

models:
    - name: dim_listings_cleansed
      description: Cleansed table which contains AIRBNB listings
      columns:

        - name: listing_id
          description: Primary key for listings
          tests: 
            - unique
            - not_null

        - name: host_id
          description: The hosts's id references host table.
          tests:
            - not_null
            - relationships:
                field: host_id
                to: ref('dim_hosts_cleansed')

        - name: room_type
          description: Type of appartment/rooms.
          tests:
            - accepted_values:
                values: ['Entire home/apt',
                         'Private room',
                         'Shared room',
                         'Hotel room']   

        - name: minimum_nights
          description: '{{doc("dim_listing_cleansed__minimum_nights")}}'
          tests:
          - positive_values


    - name: dim_listings_with_hosts
      tests:
         - dbt_expectations.expect_table_row_count_to_equal_other_table:
            compare_model: source('airbnb','listings')
      columns:
        - name: price
          tests:
            - dbt_expectations.expect_column_values_to_be_of_type:
                column_type: NUMBER
            - dbt_expectations.expect_column_quantile_values_to_be_between:
                quantile: .99
                min_value: 50 # (Optional)
                max_value: 500 # (Optional)
            - dbt_expectations.expect_column_max_to_be_between:
                max_value: 5000
                config:
                  severity: warn
            
              


    - name: dim_hosts_cleansed
      description: Cleansed table which contains hosts details
      columns:
        - name: host_id
          description: primary key for the host

        - name: host_name
          description: Name of the host

        - name: created_at
          description: Date when the listing was added
